#!/bin/bash
z=$(pwd)
a=$(cat $z/log)
if [ $a = 1 ]
then
whiptail --title "ATENÇAO" --msgbox "O Xampp será baixado e instalado" --fb 10 50
wget https://www.apachefriends.org/xampp-files/5.6.32/xampp-linux-x64-5.6.32-0-installer.run
chmod 777 xampp-linux-x64-5.6.32-0-installer.run
./xampp-linux-x64-5.6.32-0-installer.run
./server
elif [ $a = 2 ]
then
/opt/lampp/xampp startapache
/opt/lampp/xampp startmysql
whiptail --title "ATENÇAO" --msgbox "O Xampp está em execução acesse http://localhost/phpmyadmin/ ou http://localhost" --fb 12 50
./server
elif [ $a = 3 ]
then
/opt/lampp/xampp stop
whiptail --title "ATENÇAO" --msgbox "O Serviços do Xampp foram encerrados" --fb 10 50
./server
elif [ $a = 4 ]
then
thunar /opt/lampp
./server
elif [ $a = 5 ]
then
apt-get install thunar
./server
elif [ $a = 6 ]
then
shutdown now
elif [ $a = 7 ]
then
reboot
elif [ $a = 8 ]
then
htop
./server
else
whiptail --title "ATENÇÃO" --msgbox "NADA A FAZER" --fb 12 50
fi
